# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Fri May 01 08:31:01 EDT 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design Single_Cycle_Top

create_clock -name "sys_clk" -period 12.0 -waveform {0.0 6.0} [get_ports clk]
set_clock_transition 0.2 [get_clocks sys_clk]
set_load -pin_load 0.05 [get_ports {WriteData[31]}]
set_load -pin_load 0.05 [get_ports {WriteData[30]}]
set_load -pin_load 0.05 [get_ports {WriteData[29]}]
set_load -pin_load 0.05 [get_ports {WriteData[28]}]
set_load -pin_load 0.05 [get_ports {WriteData[27]}]
set_load -pin_load 0.05 [get_ports {WriteData[26]}]
set_load -pin_load 0.05 [get_ports {WriteData[25]}]
set_load -pin_load 0.05 [get_ports {WriteData[24]}]
set_load -pin_load 0.05 [get_ports {WriteData[23]}]
set_load -pin_load 0.05 [get_ports {WriteData[22]}]
set_load -pin_load 0.05 [get_ports {WriteData[21]}]
set_load -pin_load 0.05 [get_ports {WriteData[20]}]
set_load -pin_load 0.05 [get_ports {WriteData[19]}]
set_load -pin_load 0.05 [get_ports {WriteData[18]}]
set_load -pin_load 0.05 [get_ports {WriteData[17]}]
set_load -pin_load 0.05 [get_ports {WriteData[16]}]
set_load -pin_load 0.05 [get_ports {WriteData[15]}]
set_load -pin_load 0.05 [get_ports {WriteData[14]}]
set_load -pin_load 0.05 [get_ports {WriteData[13]}]
set_load -pin_load 0.05 [get_ports {WriteData[12]}]
set_load -pin_load 0.05 [get_ports {WriteData[11]}]
set_load -pin_load 0.05 [get_ports {WriteData[10]}]
set_load -pin_load 0.05 [get_ports {WriteData[9]}]
set_load -pin_load 0.05 [get_ports {WriteData[8]}]
set_load -pin_load 0.05 [get_ports {WriteData[7]}]
set_load -pin_load 0.05 [get_ports {WriteData[6]}]
set_load -pin_load 0.05 [get_ports {WriteData[5]}]
set_load -pin_load 0.05 [get_ports {WriteData[4]}]
set_load -pin_load 0.05 [get_ports {WriteData[3]}]
set_load -pin_load 0.05 [get_ports {WriteData[2]}]
set_load -pin_load 0.05 [get_ports {WriteData[1]}]
set_load -pin_load 0.05 [get_ports {WriteData[0]}]
set_load -pin_load 0.05 [get_ports {DataAddr[31]}]
set_load -pin_load 0.05 [get_ports {DataAddr[30]}]
set_load -pin_load 0.05 [get_ports {DataAddr[29]}]
set_load -pin_load 0.05 [get_ports {DataAddr[28]}]
set_load -pin_load 0.05 [get_ports {DataAddr[27]}]
set_load -pin_load 0.05 [get_ports {DataAddr[26]}]
set_load -pin_load 0.05 [get_ports {DataAddr[25]}]
set_load -pin_load 0.05 [get_ports {DataAddr[24]}]
set_load -pin_load 0.05 [get_ports {DataAddr[23]}]
set_load -pin_load 0.05 [get_ports {DataAddr[22]}]
set_load -pin_load 0.05 [get_ports {DataAddr[21]}]
set_load -pin_load 0.05 [get_ports {DataAddr[20]}]
set_load -pin_load 0.05 [get_ports {DataAddr[19]}]
set_load -pin_load 0.05 [get_ports {DataAddr[18]}]
set_load -pin_load 0.05 [get_ports {DataAddr[17]}]
set_load -pin_load 0.05 [get_ports {DataAddr[16]}]
set_load -pin_load 0.05 [get_ports {DataAddr[15]}]
set_load -pin_load 0.05 [get_ports {DataAddr[14]}]
set_load -pin_load 0.05 [get_ports {DataAddr[13]}]
set_load -pin_load 0.05 [get_ports {DataAddr[12]}]
set_load -pin_load 0.05 [get_ports {DataAddr[11]}]
set_load -pin_load 0.05 [get_ports {DataAddr[10]}]
set_load -pin_load 0.05 [get_ports {DataAddr[9]}]
set_load -pin_load 0.05 [get_ports {DataAddr[8]}]
set_load -pin_load 0.05 [get_ports {DataAddr[7]}]
set_load -pin_load 0.05 [get_ports {DataAddr[6]}]
set_load -pin_load 0.05 [get_ports {DataAddr[5]}]
set_load -pin_load 0.05 [get_ports {DataAddr[4]}]
set_load -pin_load 0.05 [get_ports {DataAddr[3]}]
set_load -pin_load 0.05 [get_ports {DataAddr[2]}]
set_load -pin_load 0.05 [get_ports {DataAddr[1]}]
set_load -pin_load 0.05 [get_ports {DataAddr[0]}]
set_load -pin_load 0.05 [get_ports MemWrite]
set_load -pin_load 0.05 [get_ports {read_dataout[31]}]
set_load -pin_load 0.05 [get_ports {read_dataout[30]}]
set_load -pin_load 0.05 [get_ports {read_dataout[29]}]
set_load -pin_load 0.05 [get_ports {read_dataout[28]}]
set_load -pin_load 0.05 [get_ports {read_dataout[27]}]
set_load -pin_load 0.05 [get_ports {read_dataout[26]}]
set_load -pin_load 0.05 [get_ports {read_dataout[25]}]
set_load -pin_load 0.05 [get_ports {read_dataout[24]}]
set_load -pin_load 0.05 [get_ports {read_dataout[23]}]
set_load -pin_load 0.05 [get_ports {read_dataout[22]}]
set_load -pin_load 0.05 [get_ports {read_dataout[21]}]
set_load -pin_load 0.05 [get_ports {read_dataout[20]}]
set_load -pin_load 0.05 [get_ports {read_dataout[19]}]
set_load -pin_load 0.05 [get_ports {read_dataout[18]}]
set_load -pin_load 0.05 [get_ports {read_dataout[17]}]
set_load -pin_load 0.05 [get_ports {read_dataout[16]}]
set_load -pin_load 0.05 [get_ports {read_dataout[15]}]
set_load -pin_load 0.05 [get_ports {read_dataout[14]}]
set_load -pin_load 0.05 [get_ports {read_dataout[13]}]
set_load -pin_load 0.05 [get_ports {read_dataout[12]}]
set_load -pin_load 0.05 [get_ports {read_dataout[11]}]
set_load -pin_load 0.05 [get_ports {read_dataout[10]}]
set_load -pin_load 0.05 [get_ports {read_dataout[9]}]
set_load -pin_load 0.05 [get_ports {read_dataout[8]}]
set_load -pin_load 0.05 [get_ports {read_dataout[7]}]
set_load -pin_load 0.05 [get_ports {read_dataout[6]}]
set_load -pin_load 0.05 [get_ports {read_dataout[5]}]
set_load -pin_load 0.05 [get_ports {read_dataout[4]}]
set_load -pin_load 0.05 [get_ports {read_dataout[3]}]
set_load -pin_load 0.05 [get_ports {read_dataout[2]}]
set_load -pin_load 0.05 [get_ports {read_dataout[1]}]
set_load -pin_load 0.05 [get_ports {read_dataout[0]}]
set_load -pin_load 0.05 [get_ports {PC_out[31]}]
set_load -pin_load 0.05 [get_ports {PC_out[30]}]
set_load -pin_load 0.05 [get_ports {PC_out[29]}]
set_load -pin_load 0.05 [get_ports {PC_out[28]}]
set_load -pin_load 0.05 [get_ports {PC_out[27]}]
set_load -pin_load 0.05 [get_ports {PC_out[26]}]
set_load -pin_load 0.05 [get_ports {PC_out[25]}]
set_load -pin_load 0.05 [get_ports {PC_out[24]}]
set_load -pin_load 0.05 [get_ports {PC_out[23]}]
set_load -pin_load 0.05 [get_ports {PC_out[22]}]
set_load -pin_load 0.05 [get_ports {PC_out[21]}]
set_load -pin_load 0.05 [get_ports {PC_out[20]}]
set_load -pin_load 0.05 [get_ports {PC_out[19]}]
set_load -pin_load 0.05 [get_ports {PC_out[18]}]
set_load -pin_load 0.05 [get_ports {PC_out[17]}]
set_load -pin_load 0.05 [get_ports {PC_out[16]}]
set_load -pin_load 0.05 [get_ports {PC_out[15]}]
set_load -pin_load 0.05 [get_ports {PC_out[14]}]
set_load -pin_load 0.05 [get_ports {PC_out[13]}]
set_load -pin_load 0.05 [get_ports {PC_out[12]}]
set_load -pin_load 0.05 [get_ports {PC_out[11]}]
set_load -pin_load 0.05 [get_ports {PC_out[10]}]
set_load -pin_load 0.05 [get_ports {PC_out[9]}]
set_load -pin_load 0.05 [get_ports {PC_out[8]}]
set_load -pin_load 0.05 [get_ports {PC_out[7]}]
set_load -pin_load 0.05 [get_ports {PC_out[6]}]
set_load -pin_load 0.05 [get_ports {PC_out[5]}]
set_load -pin_load 0.05 [get_ports {PC_out[4]}]
set_load -pin_load 0.05 [get_ports {PC_out[3]}]
set_load -pin_load 0.05 [get_ports {PC_out[2]}]
set_load -pin_load 0.05 [get_ports {PC_out[1]}]
set_load -pin_load 0.05 [get_ports {PC_out[0]}]
set_load -pin_load 0.05 [get_ports {Instr_out[31]}]
set_load -pin_load 0.05 [get_ports {Instr_out[30]}]
set_load -pin_load 0.05 [get_ports {Instr_out[29]}]
set_load -pin_load 0.05 [get_ports {Instr_out[28]}]
set_load -pin_load 0.05 [get_ports {Instr_out[27]}]
set_load -pin_load 0.05 [get_ports {Instr_out[26]}]
set_load -pin_load 0.05 [get_ports {Instr_out[25]}]
set_load -pin_load 0.05 [get_ports {Instr_out[24]}]
set_load -pin_load 0.05 [get_ports {Instr_out[23]}]
set_load -pin_load 0.05 [get_ports {Instr_out[22]}]
set_load -pin_load 0.05 [get_ports {Instr_out[21]}]
set_load -pin_load 0.05 [get_ports {Instr_out[20]}]
set_load -pin_load 0.05 [get_ports {Instr_out[19]}]
set_load -pin_load 0.05 [get_ports {Instr_out[18]}]
set_load -pin_load 0.05 [get_ports {Instr_out[17]}]
set_load -pin_load 0.05 [get_ports {Instr_out[16]}]
set_load -pin_load 0.05 [get_ports {Instr_out[15]}]
set_load -pin_load 0.05 [get_ports {Instr_out[14]}]
set_load -pin_load 0.05 [get_ports {Instr_out[13]}]
set_load -pin_load 0.05 [get_ports {Instr_out[12]}]
set_load -pin_load 0.05 [get_ports {Instr_out[11]}]
set_load -pin_load 0.05 [get_ports {Instr_out[10]}]
set_load -pin_load 0.05 [get_ports {Instr_out[9]}]
set_load -pin_load 0.05 [get_ports {Instr_out[8]}]
set_load -pin_load 0.05 [get_ports {Instr_out[7]}]
set_load -pin_load 0.05 [get_ports {Instr_out[6]}]
set_load -pin_load 0.05 [get_ports {Instr_out[5]}]
set_load -pin_load 0.05 [get_ports {Instr_out[4]}]
set_load -pin_load 0.05 [get_ports {Instr_out[3]}]
set_load -pin_load 0.05 [get_ports {Instr_out[2]}]
set_load -pin_load 0.05 [get_ports {Instr_out[1]}]
set_load -pin_load 0.05 [get_ports {Instr_out[0]}]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports reset]
set_input_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports reset]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports MemWrite]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[31]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[30]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[29]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[28]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[27]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[26]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[25]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[24]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[23]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[22]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[21]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[20]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[19]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[18]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[17]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[16]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[15]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[14]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[13]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[12]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[11]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[10]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[9]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[8]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[7]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[6]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[5]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[4]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[3]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[2]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[1]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {WriteData[0]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[31]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[30]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[29]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[28]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[27]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[26]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[25]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[24]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[23]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[22]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[21]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[20]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[19]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[18]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[17]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[16]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[15]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[14]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[13]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[12]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[11]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[10]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[9]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[8]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[7]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[6]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[5]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[4]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[3]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[2]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[1]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {DataAddr[0]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[31]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[30]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[29]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[28]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[27]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[26]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[25]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[24]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[23]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[22]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[21]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[20]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[19]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[18]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[17]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[16]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[15]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[14]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[13]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[12]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[11]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[10]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[9]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[8]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[7]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[6]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[5]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[4]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[3]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[2]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[1]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {read_dataout[0]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[31]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[30]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[29]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[28]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[27]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[26]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[25]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[24]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[23]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[22]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[21]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[20]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[19]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[18]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[17]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[16]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[15]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[14]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[13]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[12]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[11]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[10]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[9]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[8]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[7]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[6]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[5]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[4]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[3]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[2]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[1]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {PC_out[0]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[31]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[30]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[29]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[28]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[27]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[26]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[25]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[24]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[23]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[22]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[21]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[20]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[19]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[18]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[17]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[16]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[15]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[14]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[13]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[12]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[11]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[10]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[9]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[8]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[7]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[6]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[5]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[4]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[3]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[2]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[1]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -max 4.0 [get_ports {Instr_out[0]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[31]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[30]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[29]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[28]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[27]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[26]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[25]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[24]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[23]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[22]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[21]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[20]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[19]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[18]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[17]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[16]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[15]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[14]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[13]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[12]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[11]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[10]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[9]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[8]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[7]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[6]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[5]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[4]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[3]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[2]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[1]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {WriteData[0]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[31]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[30]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[29]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[28]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[27]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[26]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[25]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[24]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[23]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[22]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[21]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[20]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[19]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[18]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[17]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[16]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[15]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[14]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[13]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[12]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[11]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[10]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[9]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[8]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[7]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[6]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[5]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[4]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[3]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[2]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[1]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {DataAddr[0]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports MemWrite]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[31]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[30]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[29]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[28]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[27]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[26]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[25]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[24]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[23]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[22]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[21]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[20]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[19]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[18]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[17]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[16]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[15]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[14]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[13]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[12]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[11]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[10]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[9]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[8]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[7]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[6]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[5]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[4]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[3]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[2]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[1]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {read_dataout[0]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[31]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[30]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[29]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[28]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[27]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[26]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[25]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[24]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[23]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[22]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[21]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[20]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[19]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[18]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[17]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[16]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[15]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[14]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[13]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[12]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[11]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[10]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[9]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[8]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[7]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[6]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[5]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[4]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[3]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[2]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[1]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {PC_out[0]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[31]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[30]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[29]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[28]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[27]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[26]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[25]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[24]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[23]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[22]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[21]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[20]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[19]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[18]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[17]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[16]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[15]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[14]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[13]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[12]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[11]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[10]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[9]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[8]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[7]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[6]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[5]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[4]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[3]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[2]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[1]}]
set_output_delay -clock [get_clocks sys_clk] -add_delay -min 0.5 [get_ports {Instr_out[0]}]
set_max_fanout 20.000 [current_design]
set_max_transition 1.5 [current_design]
set_input_transition 0.5 [get_ports reset]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.5 [get_clocks sys_clk]
set_clock_uncertainty -hold 0.1 [get_clocks sys_clk]
